### PR TITLE
Switch to AGPL-3.0

### PR DESCRIPTION
**Pull request by lionkor**
LOCKED until:
- [ ] Review each individual file for third party licenses
- [ ] Implement AGPL headers into each file
- [ ] Get confirmation from all contributors/copyright owners to make the license change
- [ ] Eventually figure out bits of code of contributors that either dont agree to the license change or that are unresponsive

### CODE REVIEW

**Comment by saile515** [comment]
👍

**Comment by gamingdoom** [comment]
Okay

**Comment by WiserTixx** [comment]
Okay

**Comment by 20dka** [comment]
Okay

**Comment by O1LER** [comment]
Okay 🥳

**Comment by Mack29446** [comment]
Okay

**Comment by snepsnepsnep** [comment]
Okay

**Comment by Starystars67** [comment]
Yeah okay

**Comment by Anonymous-275** [comment]
Okay

**Comment by WhiteHusky** [comment]
I'm fine with this. Sorry for the delay.

**Review by WiserTixx — APPROVED** [review]

**Comment by SuperForz** [comment]
Okay

**Pull request merged**
